name: Log In to Azure and Redeploy

on:
  workflow_run:
    workflows:
      - ./cd-containers.yml
    types:
      - completed
  workflow_dispatch:
    inputs:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AZURE_DEV_KEY }}

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AZURE_DEV_HOST }} >> ~/.ssh/known_hosts

      # TODO: pass a parameter to know which branch to run CD on.
      # TODO: check out 'workflow_dispatch' and 'repository_dispatch'
      - name: SSH and Deploy
        run: |
          ssh ${{ secrets.AZURE_DEV_USER }}@${{ secrets.AZURE_DEV_HOST }} << 'EOF'
            cd snippets-infra/
            docker compose pull
            docker-compose -f docker-compose.dev.yml down && docker-compose -f docker-compose.dev.yml up -d
            # git pull origin main
            # Add any additional deployment commands here, e.g.,
            # or systemctl restart your-service
          EOF