name: Log In to Azure and Redeploy

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      environment:
        type: string
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use passed image value
        run:
          echo "Using image: ${{ inputs.image }}"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AZURE_DEV_KEY }}

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AZURE_DEV_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          ssh ${{ secrets.AZURE_DEV_USER }}@${{ secrets.AZURE_DEV_HOST }} << 'EOF'
            cd snippets-infra/
            docker compose pull ${{ github.event.inputs.image }}
            #docker-compose -f docker-compose.dev.yml down && docker-compose -f docker-compose.dev.yml up -d
            if [ "${{ github.event.inputs.environment }}" = "prod" ]; then
              docker-compose -f docker-compose.prod.yml down && docker-compose -f docker-compose.prod.yml up -d
            else
              docker-compose -f docker-compose.dev.yml down && docker-compose -f docker-compose.dev.yml up -d
            fi
          EOF
