name: Push Images/Containers to GHCR

on:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Check Secret Presence
        run: |
          if [ -z "${{ secrets.TEST }}" ]; then
            echo "AZURE_DEV_KEY is not set!"
            exit 1
          else
            echo "AZURE_DEV_KEY is available!"
          fi

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ github.ref == 'refs/heads/main' && format('ghcr.io/{0}:latest', env.REPO) || '' }}
            ${{ github.ref == 'refs/heads/dev' && format('ghcr.io/{0}:latest-dev', env.REPO) || '' }}
            ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
          build-args: |
            USERNAME=${{ github.actor }}
            TOKEN=${{ github.token }}



      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AZURE_DEV_KEY }}

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AZURE_DEV_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          ssh ${{ secrets.AZURE_DEV_USER }}@${{ secrets.AZURE_DEV_HOST }} << 'EOF'
            cd snippets-infra/

            if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
              docker compose pull ghcr.io/${{ env.REPO }}:latest
              docker compose up -d --no-deps ${{ env.REPO }}-app
            elif [ "${GITHUB_REF}" = "refs/heads/dev" ]; then
              docker compose pull ghcr.io/${{ env.REPO }}:latest-dev
              docker compose up -d --no-deps ${{ env.REPO }}-app
            fi
          EOF
