name: Continuos Integration with Gradle

on:
  workflow_call:
      
jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ github.actor }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Gradle
        run: ./gradlew build