name: Deploy all Services to VM

on:
  workflow_call:
    secrets:
      AZURE_KEY:
        required: true
      AZURE_USER:
        required: true
      AZURE_HOST:
        required: true

permissions:
  contents: read
  packages: write
 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AZURE_KEY }}

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          SSH_HOST=${{ secrets.AZURE_HOST }}
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          SSH_USER=${{ secrets.AZURE_USER }}
          SSH_HOST=${{ secrets.AZURE_HOST }}
          COMPOSE_FILE=${{ github.ref == 'main' && 'docker-compose.prod.yml' || 'docker-compose.dev.yml' }}
          
          ssh $SSH_USER@$SSH_HOST << EOF
            set -e
          
            cd snippets-infra || exit 1
          
            docker compose -f $COMPOSE_FILE down
          
            docker compose pull
          
            docker compose -f $COMPOSE_FILE up -d
          
          EOF
