name: Deploy all Services to VM

on:
  workflow_call:
    secrets:
      AZURE_KEY:
        required: true
      AZURE_USER:
        required: true
      AZURE_HOST:
        required: true
      COMPOSE:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AZURE_KEY }}

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          SSH_HOST=${{ secrets.AZURE_HOST }}
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          SSH_USER=${{ secrets.AZURE_USER }}
          SSH_HOST=${{ secrets.AZURE_HOST }}
          
          if [[ "${{ secrets.COMPOSE }}" == "production" ]]; then
            COMPOSE_FILE="docker-compose.prod.yml"
          else
            COMPOSE_FILE="docker-compose.dev.yml"
          fi
          
          
          ssh $SSH_USER@$SSH_HOST << EOF
            set -e
          
            cd snippets-infra || exit 1
          
            docker-compose -f $COMPOSE_FILE down
          
            docker-compose pull
          
            docker-compose -f $COMPOSE_FILE up -d
          
          EOF
