name: Deploy all Services to VM

on:
  workflow_call:
    secrets:
      AZURE_KEY:
        required: true
      AZURE_USER:
        required: true
      AZURE_HOST:
        required: true

permissions:
  contents: read
  packages: write
 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AZURE_KEY }}

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          SSH_HOST=${{ secrets.AZURE_HOST }}
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          SSH_USER=${{ secrets.AZURE_USER }}
          SSH_HOST=${{ secrets.AZURE_HOST }}
          COMPOSE_FILE=${{ env.ENVIRONMENT == 'production' && 'docker-compose.prod.yml' || 'docker-compose.dev.yml' }}
          BRANCH_NAME=${{ env.ENVIRONMENT == 'production' && 'main' || 'dev' }}
          
          ssh $SSH_USER@$SSH_HOST << EOF
            set -e
          
            cd snippets-infra || exit 1
          
            git fetch origin
            git checkout $BRANCH_NAME
            git pull origin $BRANCH_NAME
          
            echo "Backing up Azurite volume..."
            docker run --rm -v blob:/source -v /home/username/backups/azurite:/backup alpine cp -r /source /backup
          
            docker compose -f $COMPOSE_FILE down --remove-orphans
            docker network prune -f
          
            docker compose -f $COMPOSE_FILE pull
          
            docker image prune -a -f 
          
            docker compose -f $COMPOSE_FILE up -d --force-recreate --always-recreate-deps
          
          EOF
