name: Main Branch Protection

on:
  workflow_call:

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ "${GITHUB_HEAD_REF}" != "dev" ]]; then
            echo "Error: Pull request must come from the 'dev' branch"
            exit 1
          fi
